name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-16.04
#    strategy:
#      matrix:
#        node: [ '10', '8' ]
#    name: Node ${{ matrix.node }} Sample
#    steps:
#      - uses: actions/checkout@master
#      - name: Setup node
#        uses: actions/setup-node@v1
#        with:
#          version: ${{ matrix.node }}
#      - run: npm install
#      - run: npm build --if-present
#      - run: npm test

  publish-npm:
 #   needs: build
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://registry.npmjs.org/
      - name: Config Git and Push to NPM
      - run: |
           git config user.name "Actions User"
           git config user.email noreply@github.com
           npm version 1.0.$(date +%s)
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
  #  needs: build
    runs-on: ubuntu-latest
    name: Publish to GPR
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@bryancross'
      - name: Publish to GPR
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}