name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest,windows-latest]
    strategy:
      matrix:
        node: [ '10', '8' ]
    name: Node ${{ matrix.node }} Sample
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
      - run: npm install
      - run: npm build --if-present
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
           git config user.name $GITHUB_ACTOR
           git config user.email noreply@github.com
           #npm version 1.0.$(date +%s)
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@octodemov2'
      - run: | 
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
