name: Build and package 

on: [issues]

jobs:
  build:
    name: Build with Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: issc29/setup-node@master
        with:
          node_version: 10
      - run: npm install
      - run: npm build --if-present
      - run: npm test
